In [1]:
import numpy as np

np.set_printoptions(precision=3, suppress=True)

def info(name, x):
    print(f"{name}: shape={x.shape}, ndim={x.ndim}, dtype={x.dtype}")
    print(x)
    print()

In [2]:
a = np.array([1, 2, 3])          # (3,)
b = np.array([[1, 2, 3],
              [4, 5, 6]])        # (2, 3)
c = np.zeros((2, 3, 4))          # (2, 3, 4) - "тензор" 3D

info("a", a)
info("b", b)
info("c", c)

a: shape=(3,), ndim=1, dtype=int64
[1 2 3]

b: shape=(2, 3), ndim=2, dtype=int64
[[1 2 3]
 [4 5 6]]

c: shape=(2, 3, 4), ndim=3, dtype=float64
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]



In [3]:
x = np.array([1, 2, 3])
y = np.array([10, 20, 30])

info("x", x)
info("y", y)

z = x * y
info("x * y", z)

x: shape=(3,), ndim=1, dtype=int64
[1 2 3]

y: shape=(3,), ndim=1, dtype=int64
[10 20 30]

x * y: shape=(3,), ndim=1, dtype=int64
[10 40 90]



In [4]:
m = np.array([[1, 2],
              [3, 4]])

info("m", m)
info("m * 10", m * 10)

m: shape=(2, 2), ndim=2, dtype=int64
[[1 2]
 [3 4]]

m * 10: shape=(2, 2), ndim=2, dtype=int64
[[10 20]
 [30 40]]



In [5]:
A = np.array([[1, 2, 3],
              [4, 5, 6]])   # (2,3)

B = np.array([[1, 2],
              [3, 4],
              [5, 6]])      # (3,2)

info("A", A)
info("B", B)

C = A @ B
info("A @ B", C)

A: shape=(2, 3), ndim=2, dtype=int64
[[1 2 3]
 [4 5 6]]

B: shape=(3, 2), ndim=2, dtype=int64
[[1 2]
 [3 4]
 [5 6]]

A @ B: shape=(2, 2), ndim=2, dtype=int64
[[22 28]
 [49 64]]



In [6]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[10, 20],
              [30, 40]])

info("A", A)
info("B", B)

info("A * B (elemwise)", A * B)
info("A @ B (matmul)", A @ B)

A: shape=(2, 2), ndim=2, dtype=int64
[[1 2]
 [3 4]]

B: shape=(2, 2), ndim=2, dtype=int64
[[10 20]
 [30 40]]

A * B (elemwise): shape=(2, 2), ndim=2, dtype=int64
[[ 10  40]
 [ 90 160]]

A @ B (matmul): shape=(2, 2), ndim=2, dtype=int64
[[ 70 100]
 [150 220]]



In [7]:
M = np.array([[1, 2, 3],
              [4, 5, 6]])     # (2,3)
v = np.array([10, 20, 30])    # (3,)

info("M", M)
info("v", v)

info("M + v", M + v)

M: shape=(2, 3), ndim=2, dtype=int64
[[1 2 3]
 [4 5 6]]

v: shape=(3,), ndim=1, dtype=int64
[10 20 30]

M + v: shape=(2, 3), ndim=2, dtype=int64
[[11 22 33]
 [14 25 36]]



In [8]:
col = np.array([100, 200])      # (2,)
info("col", col)

col2 = col[:, None]             # (2,1)
info("col[:, None]", col2)

info("M + col[:, None]", M + col2)

col: shape=(2,), ndim=1, dtype=int64
[100 200]

col[:, None]: shape=(2, 1), ndim=2, dtype=int64
[[100]
 [200]]

M + col[:, None]: shape=(2, 3), ndim=2, dtype=int64
[[101 102 103]
 [204 205 206]]



In [9]:
weights = np.array([1.0, 0.1, 10.0])  # (3,)
info("weights", weights)
info("M * weights", M * weights)

weights: shape=(3,), ndim=1, dtype=float64
[ 1.   0.1 10. ]

M * weights: shape=(2, 3), ndim=2, dtype=float64
[[ 1.   0.2 30. ]
 [ 4.   0.5 60. ]]



In [10]:
batch_A = np.random.randn(5, 2, 3)  # 5 матриц (2x3)
batch_B = np.random.randn(5, 3, 4)  # 5 матриц (3x4)

info("batch_A", batch_A)
info("batch_B", batch_B)

batch_C = batch_A @ batch_B         # (5,2,4)
info("batch_A @ batch_B", batch_C)

batch_A: shape=(5, 2, 3), ndim=3, dtype=float64
[[[-0.564 -0.559 -0.711]
  [ 0.892 -0.5   -0.654]]

 [[ 0.03   0.422  1.636]
  [ 1.362 -1.648  2.499]]

 [[ 0.358  0.576  1.518]
  [-0.33  -0.376 -0.927]]

 [[ 0.999 -1.625  0.628]
  [ 0.934  0.346 -1.057]]

 [[ 0.295  0.956 -2.268]
  [-0.79  -0.293 -0.402]]]

batch_B: shape=(5, 3, 4), ndim=3, dtype=float64
[[[ 0.107 -0.513  1.087 -1.122]
  [ 0.494  0.825  1.006  0.126]
  [ 0.942 -1.786 -0.246  1.484]]

 [[-0.204  0.47  -0.267 -0.148]
  [-0.238  0.447 -0.677  0.368]
  [-1.178 -0.293  0.579 -0.862]]

 [[-1.091  1.572  0.366  0.613]
  [ 0.04  -1.178 -0.752 -0.234]
  [ 0.196  1.006 -0.347  1.434]]

 [[-0.058  1.575 -1.489 -0.753]
  [-0.413  0.256 -0.67   0.01 ]
  [ 0.976  0.081 -1.229 -0.782]]

 [[ 0.905  0.909 -1.211  1.731]
  [-0.704 -0.348  2.012  0.777]
  [ 0.709  0.595  0.484  0.222]]]

batch_A @ batch_B: shape=(5, 2, 4), ndim=3, dtype=float64
[[[-1.006  1.099 -1.001 -0.493]
  [-0.768  0.297  0.626 -2.034]]

 [[-2.035 -0.277  0.652 -1.2

In [11]:
A = np.random.randn(5, 2, 3)   # (5,2,3)
B = np.random.randn(3, 4)      # (3,4) без batch

info("A", A)
info("B", B)

C = A @ B                      # (5,2,4) — B “растянулся” на 5
info("A @ B", C)

A: shape=(5, 2, 3), ndim=3, dtype=float64
[[[ 0.728  0.269 -1.109]
  [-0.51   0.392 -0.197]]

 [[ 1.698  0.115 -0.261]
  [ 0.955  2.044 -0.677]]

 [[-0.173 -0.068  1.115]
  [-0.823  1.561  0.211]]

 [[-0.523  1.156  1.202]
  [ 1.194  0.014 -0.56 ]]

 [[-0.182 -0.09   1.386]
  [ 0.845  0.543 -0.005]]]

B: shape=(3, 4), ndim=2, dtype=float64
[[ 0.585  0.226  0.184  1.528]
 [ 0.454 -1.818 -1.164  1.658]
 [ 0.829  0.508 -0.019  0.565]]

A @ B: shape=(5, 2, 4), ndim=3, dtype=float64
[[[-0.371 -0.888 -0.158  0.933]
  [-0.284 -0.929 -0.547 -0.24 ]]

 [[ 0.83   0.042  0.184  2.637]
  [ 0.927 -3.844 -2.191  4.465]]

 [[ 0.793  0.65   0.026  0.253]
  [ 0.403 -2.916 -1.973  1.45 ]]

 [[ 1.216 -1.609 -1.464  1.796]
  [ 0.241 -0.04   0.214  1.531]]

 [[ 1.002  0.827  0.045  0.355]
  [ 0.738 -0.799 -0.477  2.189]]]



In [12]:
A = np.random.randn(2, 3)
B = np.random.randn(2, 3)

info("A", A)
info("B", B)

try:
    A @ B
except ValueError as e:
    print("Ошибка:", e)

A: shape=(2, 3), ndim=2, dtype=float64
[[-1.06   0.272  1.437]
 [-0.848  0.159  1.762]]

B: shape=(2, 3), ndim=2, dtype=float64
[[-0.583 -0.666  2.508]
 [ 0.229  0.379 -0.774]]

Ошибка: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)


In [13]:
M = np.zeros((2, 3))
v = np.zeros((2,))  # (2,) не совместимо с (2,3) по последней оси

info("M", M)
info("v", v)

try:
    M + v
except ValueError as e:
    print("Ошибка:", e)

# исправление: сделать v столбцом
info("M + v[:, None]", M + v[:, None])

M: shape=(2, 3), ndim=2, dtype=float64
[[0. 0. 0.]
 [0. 0. 0.]]

v: shape=(2,), ndim=1, dtype=float64
[0. 0.]

Ошибка: operands could not be broadcast together with shapes (2,3) (2,) 
M + v[:, None]: shape=(2, 3), ndim=2, dtype=float64
[[0. 0. 0.]
 [0. 0. 0.]]

